#!/bin/bash
#
Moleculetemp=$1
sed -i 's/ 1 / H  /g' $Moleculetemp
sed -i 's/ 2 / He  /g' $Moleculetemp 
sed -i 's/ 3 / Li  /g' $Moleculetemp
sed -i 's/ 4 / Be  /g' $Moleculetemp
sed -i 's/ 5 / B  /g' $Moleculetemp
sed -i 's/ 6 / C  /g' $Moleculetemp
sed -i 's/ 7 / N  /g' $Moleculetemp
sed -i 's/ 8 / O  /g' $Moleculetemp
sed -i 's/ 9 / F  /g' $Moleculetemp
sed -i 's/ 10 / Ne  /g' $Moleculetemp
sed -i 's/ 11 / Na  /g' $Moleculetemp 
sed -i 's/ 12 / Mg  /g' $Moleculetemp
sed -i 's/ 13 / Al  /g' $Moleculetemp
sed -i 's/ 14 / Si  /g' $Moleculetemp
sed -i 's/ 15 / P  /g' $Moleculetemp
sed -i 's/ 16 / S  /g' $Moleculetemp
sed -i 's/ 17 / Cl  /g' $Moleculetemp
sed -i 's/ 18 / Ar  /g' $Moleculetemp
sed -i 's/ 19 / K  /g' $Moleculetemp
sed -i 's/ 20 / Ca  /g' $Moleculetemp 
sed -i 's/ 21 / Sc  /g' $Moleculetemp
sed -i 's/ 22 / Ti  /g' $Moleculetemp
sed -i 's/ 23 / V  /g' $Moleculetemp
sed -i 's/ 24 / Cr  /g' $Moleculetemp
sed -i 's/ 25 / Mn  /g' $Moleculetemp
sed -i 's/ 26 / Fe  /g' $Moleculetemp
sed -i 's/ 27 / Co  /g' $Moleculetemp
sed -i 's/ 28 / Ni  /g' $Moleculetemp
sed -i 's/ 29 / Cu  /g' $Moleculetemp 
sed -i 's/ 30 / Zn  /g' $Moleculetemp
sed -i 's/ 31 / Ga  /g' $Moleculetemp
sed -i 's/ 32 / Ge  /g' $Moleculetemp
sed -i 's/ 33 / As  /g' $Moleculetemp
sed -i 's/ 34 / Se  /g' $Moleculetemp
sed -i 's/ 35 / Br  /g' $Moleculetemp
sed -i 's/ 36 / Kr  /g' $Moleculetemp
sed -i 's/ 37 / Rb  /g' $Moleculetemp
sed -i 's/ 38 / Sr  /g' $Moleculetemp
sed -i 's/ 39 / Y  /g' $Moleculetemp
sed -i 's/ 40 / Zr  /g' $Moleculetemp
sed -i 's/ 41 / Nb  /g' $Moleculetemp
sed -i 's/ 42 / Mo  /g' $Moleculetemp
sed -i 's/ 43 / Tc  /g' $Moleculetemp 
sed -i 's/ 44 / Ru  /g' $Moleculetemp
sed -i 's/ 45 / Rh  /g' $Moleculetemp
sed -i 's/ 46 / Pd  /g' $Moleculetemp
sed -i 's/ 47 / Ag  /g' $Moleculetemp
sed -i 's/ 48 / Cd  /g' $Moleculetemp
sed -i 's/ 49 / In  /g' $Moleculetemp
sed -i 's/ 50 / Sn  /g' $Moleculetemp
sed -i 's/ 51 / Sb  /g' $Moleculetemp
sed -i 's/ 52 / Te  /g' $Moleculetemp 
sed -i 's/ 53 / I  /g' $Moleculetemp
sed -i 's/ 54 / Xe  /g' $Moleculetemp
sed -i 's/ 55 / Cs  /g' $Moleculetemp
sed -i 's/ 56 / Ba  /g' $Moleculetemp
sed -i 's/ 57 / La  /g' $Moleculetemp
sed -i 's/ 58 / Ce /g' $Moleculetemp
sed -i 's/ 59 / Pr  /g' $Moleculetemp
sed -i 's/ 60 / Nd  /g' $Moleculetemp
sed -i 's/ 61 / Pm  /g' $Moleculetemp 
sed -i 's/ 62 / Sm  /g' $Moleculetemp
sed -i 's/ 63 / Eu  /g' $Moleculetemp
sed -i 's/ 64 / Gd  /g' $Moleculetemp
sed -i 's/ 65 / Tb  /g' $Moleculetemp
sed -i 's/ 66 / Dy  /g' $Moleculetemp
sed -i 's/ 67 / Ho  /g' $Moleculetemp
sed -i 's/ 68 / Er /g' $Moleculetemp
sed -i 's/ 69 / Tm  /g' $Moleculetemp
sed -i 's/ 70 / Yb  /g' $Moleculetemp
sed -i 's/ 71 / Lu  /g' $Moleculetemp
sed -i 's/ 72 / Hf  /g' $Moleculetemp
sed -i 's/ 73 / Ta  /g' $Moleculetemp
sed -i 's/ 74 / W  /g' $Moleculetemp
sed -i 's/ 75 / Re  /g' $Moleculetemp 
sed -i 's/ 76 / Os  /g' $Moleculetemp
sed -i 's/ 77 / Ir  /g' $Moleculetemp
sed -i 's/ 78 / Pt  /g' $Moleculetemp
sed -i 's/ 79 / Au  /g' $Moleculetemp
sed -i 's/ 80 / Hg  /g' $Moleculetemp
sed -i 's/ 81 / Tl  /g' $Moleculetemp
sed -i 's/ 82 / Pb  /g' $Moleculetemp
sed -i 's/ 83 / Bi  /g' $Moleculetemp
sed -i 's/ 84 / Po  /g' $Moleculetemp
sed -i 's/ 85 / At  /g' $Moleculetemp
sed -i 's/ 86 / Rn  /g' $Moleculetemp
sed -i 's/ 87 / Fr  /g' $Moleculetemp
sed -i 's/ 88 / Ra  /g' $Moleculetemp
sed -i 's/ 89 / Ac  /g' $Moleculetemp
sed -i 's/ 90 / Th  /g' $Moleculetemp
sed -i 's/ 91 / Pa  /g' $Moleculetemp
sed -i 's/ 92 / U  /g' $Moleculetemp
sed -i 's/ 93 / Np  /g' $Moleculetemp
sed -i 's/ 94 / Pu  /g' $Moleculetemp
sed -i 's/ 95 / Am  /g' $Moleculetemp
sed -i 's/ 96 / Cm  /g' $Moleculetemp
sed -i 's/ 97 / Bk  /g' $Moleculetemp
sed -i 's/ 98 / Cf  /g' $Moleculetemp
sed -i 's/ 99 / Es  /g' $Moleculetemp
sed -i 's/ 100 / Fm  /g' $Moleculetemp
sed -i 's/ 101 / Md  /g' $Moleculetemp 
sed -i 's/ 102 / No  /g' $Moleculetemp
sed -i 's/ 103 / Lr  /g' $Moleculetemp
sed -i 's/ 104 / Rf  /g' $Moleculetemp
sed -i 's/ 105 / Db  /g' $Moleculetemp
sed -i 's/ 106 / Sg  /g' $Moleculetemp
sed -i 's/ 107 / Bh  /g' $Moleculetemp
sed -i 's/ 108 / Hs  /g' $Moleculetemp
sed -i 's/ 109 / Mt  /g' $Moleculetemp
sed -i 's/ 110 / Ds  /g' $Moleculetemp 
sed -i 's/ 111 / Rg  /g' $Moleculetemp
sed -i 's/ 112 / Cn  /g' $Moleculetemp
sed -i 's/ 113 / Nh  /g' $Moleculetemp
sed -i 's/ 114 / Fl  /g' $Moleculetemp
sed -i 's/ 115 / Mc  /g' $Moleculetemp
sed -i 's/ 116 / Lv  /g' $Moleculetemp
sed -i 's/ 117 / Ts  /g' $Moleculetemp
sed -i 's/ 118 / Og  /g' $Moleculetemp
