#!/bin/bash
#
Moleculetemp=$1
sed -i 's/ H / 1.0  /g' $Moleculetemp  
sed -i 's/ He / 2.0  /g' $Moleculetemp
sed -i 's/ Li / 3.0  /g' $Moleculetemp
sed -i 's/ Be / 4.0  /g' $Moleculetemp
sed -i 's/ B / 5.0  /g' $Moleculetemp
sed -i 's/ C / 6.0  /g' $Moleculetemp
sed -i 's/ N / 7.0  /g' $Moleculetemp
sed -i 's/ O / 8.0  /g' $Moleculetemp  
sed -i 's/ F / 9.0  /g' $Moleculetemp 
sed -i 's/ Ne / 10.0  /g' $Moleculetemp
sed -i 's/ Na / 11.0  /g' $Moleculetemp
sed -i 's/ Mg / 12.0  /g' $Moleculetemp
sed -i 's/ Al / 13.0  /g' $Moleculetemp
sed -i 's/ Si / 14.0  /g' $Moleculetemp
sed -i 's/ P / 15.0  /g' $Moleculetemp
sed -i 's/ S / 16.0  /g' $Moleculetemp
sed -i 's/ Cl / 17.0  /g' $Moleculetemp
sed -i 's/ Ar / 18.0  /g' $Moleculetemp
sed -i 's/ K / 19.0  /g' $Moleculetemp
sed -i 's/ Ca / 20.0  /g' $Moleculetemp
sed -i 's/ Sc / 21.0  /g' $Moleculetemp  
sed -i 's/ Ti / 22.0  /g' $Moleculetemp 
sed -i 's/ V / 23.0  /g' $Moleculetemp
sed -i 's/ Cr / 24.0  /g' $Moleculetemp
sed -i 's/ Mn / 25.0  /g' $Moleculetemp
sed -i 's/ Fe / 26.0  /g' $Moleculetemp
sed -i 's/ Co / 27.0  /g' $Moleculetemp
sed -i 's/ Ni / 28.0  /g' $Moleculetemp
sed -i 's/ Cu / 29.0  /g' $Moleculetemp
sed -i 's/ Zn / 30.0  /g' $Moleculetemp
sed -i 's/ Ga / 31.0  /g' $Moleculetemp
sed -i 's/ Ge / 32.0  /g' $Moleculetemp
sed -i 's/ As / 33.0  /g' $Moleculetemp
sed -i 's/ Se / 34.0  /g' $Moleculetemp  
sed -i 's/ Br / 35.0  /g' $Moleculetemp 
sed -i 's/ Kr / 36.0  /g' $Moleculetemp
sed -i 's/ Rb / 37.0  /g' $Moleculetemp
sed -i 's/ Sr / 38.0  /g' $Moleculetemp
sed -i 's/ Y / 39.0  /g' $Moleculetemp
sed -i 's/ Zr / 40.0  /g' $Moleculetemp
sed -i 's/ Nb / 41.0  /g' $Moleculetemp
sed -i 's/ Mo / 42.0  /g' $Moleculetemp
sed -i 's/ Tc / 43.0  /g' $Moleculetemp
sed -i 's/ Ru / 44.0  /g' $Moleculetemp
sed -i 's/ Rh / 45.0  /g' $Moleculetemp
sed -i 's/ Pd / 46.0  /g' $Moleculetemp
sed -i 's/ Ag / 47.0  /g' $Moleculetemp  
sed -i 's/ Cd / 48.0  /g' $Moleculetemp 
sed -i 's/ In / 49.0  /g' $Moleculetemp
sed -i 's/ Sn / 50.0  /g' $Moleculetemp
sed -i 's/ Sb / 51.0  /g' $Moleculetemp
sed -i 's/ Te / 52.0  /g' $Moleculetemp
sed -i 's/ I / 53.0  /g' $Moleculetemp
sed -i 's/ Xe / 54.0  /g' $Moleculetemp
sed -i 's/ Cs / 55.0  /g' $Moleculetemp
sed -i 's/ Ba / 56.0  /g' $Moleculetemp
sed -i 's/ La / 57.0  /g' $Moleculetemp
sed -i 's/ Ce / 58.0  /g' $Moleculetemp  
sed -i 's/ Pr / 59.0  /g' $Moleculetemp
sed -i 's/ Nd / 60.0  /g' $Moleculetemp
sed -i 's/ Pm / 61.0  /g' $Moleculetemp
sed -i 's/ Sm / 62.0  /g' $Moleculetemp
sed -i 's/ Eu / 63.0  /g' $Moleculetemp
sed -i 's/ Gd / 64.0  /g' $Moleculetemp
sed -i 's/ Tb / 65.0  /g' $Moleculetemp  
sed -i 's/ Dy / 66.0  /g' $Moleculetemp 
sed -i 's/ Ho / 67.0  /g' $Moleculetemp
sed -i 's/ Er / 68.0  /g' $Moleculetemp
sed -i 's/ Tm / 69.0  /g' $Moleculetemp
sed -i 's/ Yb / 70.0  /g' $Moleculetemp
sed -i 's/ Lu / 71.0  /g' $Moleculetemp
sed -i 's/ Hf / 72.0  /g' $Moleculetemp
sed -i 's/ Ta / 73.0  /g' $Moleculetemp
sed -i 's/ W / 74.0  /g' $Moleculetemp
sed -i 's/ Re / 75.0  /g' $Moleculetemp
sed -i 's/ Os / 76.0  /g' $Moleculetemp
sed -i 's/ Ir / 77.0  /g' $Moleculetemp
sed -i 's/ Pt / 78.0  /g' $Moleculetemp  
sed -i 's/ Au / 79.0  /g' $Moleculetemp 
sed -i 's/ Hg / 80.0  /g' $Moleculetemp
sed -i 's/ Tl / 81.0  /g' $Moleculetemp
sed -i 's/ Pb / 82.0  /g' $Moleculetemp
sed -i 's/ Bi / 83.0  /g' $Moleculetemp
sed -i 's/ Po / 84.0  /g' $Moleculetemp
sed -i 's/ At / 85.0  /g' $Moleculetemp
sed -i 's/ Rn / 86.0  /g' $Moleculetemp
sed -i 's/ Fr / 87.0  /g' $Moleculetemp
sed -i 's/ Ra / 88.0  /g' $Moleculetemp
sed -i 's/ Ac / 89.0  /g' $Moleculetemp
sed -i 's/ Th / 90.0  /g' $Moleculetemp
sed -i 's/ Pa / 91.0  /g' $Moleculetemp  
sed -i 's/ U / 92.0  /g' $Moleculetemp 
sed -i 's/ Np / 93.0  /g' $Moleculetemp
sed -i 's/ Pu / 94.0  /g' $Moleculetemp
sed -i 's/ Am / 95.0  /g' $Moleculetemp
sed -i 's/ Cm / 96.0  /g' $Moleculetemp
sed -i 's/ Bk / 97.0  /g' $Moleculetemp
sed -i 's/ Cf / 98.0  /g' $Moleculetemp
sed -i 's/ Es / 99.0  /g' $Moleculetemp
sed -i 's/ Fm / 100.0  /g' $Moleculetemp
sed -i 's/ Md / 101.0  /g' $Moleculetemp
sed -i 's/ No / 102.0  /g' $Moleculetemp
sed -i 's/ Lr / 103.0  /g' $Moleculetemp
sed -i 's/ Rf / 104.0  /g' $Moleculetemp  
sed -i 's/ Db / 105.0  /g' $Moleculetemp 
sed -i 's/ Sg / 106.0  /g' $Moleculetemp
sed -i 's/ Bh / 107.0  /g' $Moleculetemp
sed -i 's/ Hs / 108.0  /g' $Moleculetemp
sed -i 's/ Mt / 109.0  /g' $Moleculetemp
sed -i 's/ Ds / 110.0  /g' $Moleculetemp
sed -i 's/ Rg / 111.0  /g' $Moleculetemp
sed -i 's/ Cn / 112.0  /g' $Moleculetemp
sed -i 's/ Nh / 113.0  /g' $Moleculetemp
sed -i 's/ Fl / 114.0  /g' $Moleculetemp
sed -i 's/ Mc / 115.0  /g' $Moleculetemp
sed -i 's/ Lv / 116.0  /g' $Moleculetemp
sed -i 's/ Ts / 117.0  /g' $Moleculetemp
sed -i 's/ Og / 118.0  /g' $Moleculetemp
